apiVersion: v1
kind: Service
metadata:
  name: hello-app-blue
  namespace: hello-app
  labels:
    {{- include "hello-app.labels" . | nindent 4 }}
    slot: blue
spec:
  type: ClusterIP
  selector:
    app: hello-app
    slot: blue
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
